add tags
rilian/newsletter pull request #45
Opened 2016-10-04 13:19 UTC by pavel-zhuravlyov

2016-10-04 13:34 UTC, rilian commented
please attach screenshots from both site and email with tags

2016-10-04 13:42 UTC, pavel-zhuravlyov commented
Field from link form
![image](https://cloud.githubusercontent.com/assets/9430566/19076330/0858b576-8a51-11e6-9eac-2add812a07b9.png)

Links list
![image](https://cloud.githubusercontent.com/assets/9430566/19076410/564a5ae6-8a51-11e6-81aa-27e69c39fddc.png)

Email
![image](https://cloud.githubusercontent.com/assets/9430566/19076442/727c3cd4-8a51-11e6-89f3-b9e9f432bdf9.png)

2016-10-04 13:54 UTC, rilian commented
ok, but plz make tag a link to a public search of Links with this tag

2016-10-04 14:08 UTC, sudodoki commented on Gemfile
> +gem "select2-rails"
why double quote instead single?

2016-10-04 14:10 UTC, tilast commented on app/assets/javascripts/tags.js
> +  });
plz prefer using 2 space over the tabs

2016-10-04 14:11 UTC, sudodoki commented on app/assets/javascripts/tags.js
> +  });
there's editorconfig in repo - please enable this in your editor

2016-10-04 14:11 UTC, tilast commented
generally nice

2016-10-04 14:11 UTC, sudodoki commented on app/assets/javascripts/tags.js
> +$( document ).ready(function() {
no need for spaces here

2016-10-04 16:00 UTC, tilast approved these changes
ok for me but let's wait for @rilian review

2016-10-05 09:38 UTC, rilian requested changes
i am not sure links search is working for guests

2016-10-05 09:38 UTC, rilian commented on app/controllers/links_controller.rb
> +      end.page(params[:page]).order('issue_id IS NOT NULL').order(id: :desc)
use variables instead of chaining to `end`

2016-10-05 09:38 UTC, rilian commented on app/views/issue_mailer/notify_subscribers.slim
> +            span style="display: inline-block; border: 1px solid black; border-radius: 5px; min-width: 40px; margin: 0 10px; padding: 0 5px; text-align: center;" #{tag}
no link here

2016-10-05 09:53 UTC, rilian approved these changes

2016-10-05 09:54 UTC, rilian commented
not approved yet. testing github UI :)

2016-10-05 09:55 UTC, rilian requested changes
plz review comments above

2016-10-05 14:42 UTC, tilast commented on app/services/link_filter.rb
> +          Link.tagged_with(@params[:tag])
i think we should also add a constraint for the links to check issue id
we should not show links without the issue

2016-10-05 14:54 UTC, rilian commented on app/services/link_filter.rb
> +          Link.tagged_with(@params[:tag])
also links to unpublished issues should not be searchable

2016-10-05 15:04 UTC, tilast commented on app/services/link_filter.rb
> +          Link.tagged_with(@params[:tag])
oh, I meant this

2016-10-05 18:52 UTC, tilast approved these changes
looks ok for me but just fix two comments

2016-10-05 18:52 UTC, tilast commented on app/views/links/search_by_tag.slim
> +              br
it will not be under the `if` - you should add a space here

2016-10-05 18:52 UTC, tilast commented on app/views/links/search_by_tag.slim
> +  .column class='three-fourths'
just
```slim
  .column.three-fourths
```

2016-10-05 19:58 UTC, rilian commented
@tilast plz merge once comments will be fixed

2016-10-05 20:50 UTC, tilast commented
@pavel-zhuravlyov nice to merge

2016-10-05 20:54 UTC, merged