add tests
rilian/newsletter pull request #46
Opened 2016-10-10 09:06 UTC by pavel-zhuravlyov

2016-10-10 10:13 UTC, tilast commented on app/services/link_filter.rb
> +        []
use `Link.none`

2016-10-10 11:03 UTC, denysxftr requested changes
nice
c one comment

2016-10-10 11:03 UTC, ololyay commented on spec/models/issue_spec.rb
> +        issue.save
why?

2016-10-12 13:55 UTC, tilast requested changes
plz copy-paste `.rubocop` file from Railsreactor/seashells-api and add gem `rubocop`

2016-10-12 13:55 UTC, tilast commented on app/controllers/application_controller.rb
> +      f.json { render json: { errors: [*e.message] }, status: :not_found }
no need for that line

2016-10-12 13:55 UTC, tilast commented on app/services/link_filter.rb
> +          .page(@params[:page]).order(id: :desc)
I'd write it like
```ruby
Link
  .joins(:issue)
  .where.not(issue_id: nil, issues: { sent_at: nil })
  .tagged_with(@params[:tag])
  .page(@params[:page])
  .order(id: :desc)
```

2016-10-12 13:55 UTC, tilast commented on spec/controllers/home/index_spec.rb
> +      expect(assigns(:issues)).to match_array Issue.all
plz create several issues like
```ruby
  let!(:issue_1) { create :issue }
```

2016-10-12 13:55 UTC, tilast commented on spec/controllers/issues/create_spec.rb
> +        post :create, issue: {title: '', desc: ''}
we should also add `rubocop` to the project

2016-10-12 13:55 UTC, tilast commented on spec/controllers/issues/create_spec.rb
> +        post :create, issue: {title: '', desc: ''}
`{ title: '', desc: '' }`

2016-10-12 13:55 UTC, tilast commented on spec/controllers/issues/create_spec.rb
> +        post :create, issue: {title: '', desc: ''}
same here

2016-10-12 13:55 UTC, tilast commented on spec/controllers/issues/send_issue_spec.rb
> +        issue.update(sent_at: Time.zone.now)
as you used `let()` to create an issue, it's better just to redefine `issue` here before `it` like
```ruby
  let(:issue) { create :issue, sent_at: Time.zone.now }
```

2016-10-12 13:55 UTC, tilast commented on spec/controllers/issues/show_spec.rb
> +
needless space

2016-10-12 13:55 UTC, tilast commented on spec/controllers/issues/show_spec.rb
> +          issue.update(sent_at: Time.zone.now)
same here

2016-10-12 13:55 UTC, tilast commented on spec/controllers/issues/show_spec.rb
> +        sign_in manager
it should be moved to `before`

2016-10-12 13:55 UTC, tilast commented on spec/controllers/issues/show_spec.rb
> +        sign_in manager
`before`

2016-10-12 13:55 UTC, tilast commented on spec/controllers/issues/update_spec.rb
> +        allow_any_instance_of(Issue).to receive(:update).and_return(false)
move it to `before` plz

2016-10-12 13:55 UTC, tilast commented on spec/controllers/links/create_spec.rb
> +        expect(assigns(:link).errors.full_messages).to include "Url can't be blank"
let's check the all the `full_messages` object here

2016-10-12 13:55 UTC, tilast commented on spec/controllers/links/index_spec.rb
> +          sign_in(manager)
move to `before`

2016-10-12 13:55 UTC, tilast commented on spec/controllers/links/index_spec.rb
> +    context 'with manager' do
`for manager` is more suitable here

2016-10-12 13:55 UTC, tilast commented on spec/controllers/links/index_spec.rb
> +    context 'with guest' do
`for guest`

2016-10-12 13:55 UTC, tilast commented on spec/controllers/links/index_spec.rb
> +          Link.without_issue.update_all(issue_id: issue.id)
it's better to omit it putting issue id to link directly in factory

2016-10-12 13:55 UTC, tilast commented on spec/controllers/links/index_spec.rb
> +          issue.update(sent_at: Time.zone.now)
put in `issue` factory

2016-10-12 13:55 UTC, tilast commented on spec/controllers/links/new_spec.rb
> +    before { sign_in manager}
wrong indentation, we definitely need `rubocop` :)

2016-10-12 13:55 UTC, tilast commented on spec/controllers/links/new_spec.rb
> +        get :new, link: {url: 'abc'}
wrong hash indentations

2016-10-12 13:55 UTC, tilast commented on spec/controllers/managers/create_spec.rb
> +        expect(assigns(:manager)).to eq Manager.where(email: 'mail@example.com').first
`Manager.fint_by_email('mail@example.com')`

2016-10-12 13:55 UTC, tilast commented on spec/controllers/managers/update_spec.rb
> +        allow_any_instance_of(Manager).to receive(:update).and_return(false)
move to `before`

2016-10-12 13:55 UTC, tilast commented on spec/controllers/subscribers/create_spec.rb
> +        subscriber = Subscriber.where(email: 'mail@example.com').first
`find_by_email`

2016-10-12 13:55 UTC, tilast commented on spec/helpers/form_spec.rb
> +      allow_any_instance_of(Manager).to receive(:persisted?).and_return(true)
`before`

2016-10-12 13:55 UTC, tilast commented on spec/mailers/issue_mailer_spec.rb
> +      issue.update(sent_at: Time.zone.now)
plz do that in factory defining at the top of file

2016-10-12 13:55 UTC, tilast commented on spec/models/issue_spec.rb
> +    it { is_expected.to have_db_column(:title).of_type(:string) }
I do not see `id` field :)

2016-10-12 13:55 UTC, tilast commented on spec/models/link_spec.rb
> +    it { is_expected.to have_db_column(:title).of_type(:string) }
same here

2016-10-13 12:02 UTC, denysxftr requested changes
awesome but c 2 comments

2016-10-13 12:02 UTC, ololyay commented on app/helpers/application_helper.rb
> +    when :alert then 'flash-warn'
i can't stop myself

```ruby
{ notice: '', error: 'flash-error', alert: 'flash-warn'}[level]
```

2016-10-13 12:02 UTC, ololyay commented on app/helpers/application_helper.rb
> +    if (icon = options[:icon]).present?
do not assign vars in if
make it
```ruby
if options[:icon].present?
```
and then in if body use options[:icon] instead of icon var

2016-10-13 12:11 UTC, denysxftr approved these changes

2016-10-13 12:13 UTC, tilast approved these changes

2016-10-13 12:14 UTC, tilast commented
@rilian I will merge this one

2016-10-13 12:14 UTC, merged