Rails5
rilian/newsletter pull request #47
Opened 2016-10-18 16:42 UTC by pavel-zhuravlyov

2016-10-18 16:46 UTC, tilast commented
@rilian plz consider adding open-source travis here or move it to gitlab

2016-10-18 16:57 UTC, tilast requested changes

2016-10-18 16:57 UTC, tilast commented on app/views/links/index.slim
> +             td #{link.id}
I guess you've missed on space before `td`

2016-10-18 16:57 UTC, tilast commented on app/views/links/index.slim
> +    /      = paginate @links
why is this code commented?

2016-10-18 16:57 UTC, tilast commented on .semaphore-cache/rubocop_cache/rubocop_cache/1567e4615c9958245b9099e70815f129/_/ffe1ebd764eac00596ea3b511eeb167c
> +[]
plz remove cache files

2016-10-18 17:50 UTC, tilast approved these changes

2016-10-19 08:11 UTC, rilian requested changes

2016-10-19 08:11 UTC, rilian commented on app/views/links/index.slim
> +                  | by #{link.manager.email.split('@').first}
.manager can be nil

2016-10-19 08:11 UTC, rilian commented on spec/controllers/links/index_spec.rb
> -          expect(assigns(:links)).not_to include second_link
why the test is removed?

2016-10-19 08:11 UTC, rilian commented on spec/services/link_filter_spec.rb
> -        expect(result).to eq []
why the test is removed?

2016-10-19 12:11 UTC, pavel-zhuravlyov commented
plz review

2016-10-20 16:09 UTC, tilast requested changes

2016-10-20 16:09 UTC, tilast commented on spec/controllers/links/index_spec.rb
> +
plz check `@links` contains something

2016-10-20 16:09 UTC, tilast commented on spec/controllers/links/index_spec.rb
> +
same here

2016-10-20 19:07 UTC, tilast approved these changes

2016-10-21 11:31 UTC, tilast requested changes

2016-10-21 11:31 UTC, tilast commented on config/secrets.yml
> +  secret_key_base: 11d2ab90ec2c6d0a00e25ece0df26703ec6ec00b8f4c5602e2f4f26fd8ac3529d46c9f85bec1613d0b92454c2d54e443a441cbd5e25f07cbc40b0abbdd027728
why?

2016-10-31 17:27 UTC, pavel-zhuravlyov commented
plz review

2016-11-08 15:48 UTC, merged